//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Trainer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Trainings
    {
        public int Id { get; set; }
        public string Type { get; set; }
        public string Name { get; set; }
        public Nullable<int> Lessons { get; set; }
        public string Discription { get; set; }
    }
}
